/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package custom;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.Icon;

/**
 *
 * @author fatiq
 */
public class MenuCustom extends javax.swing.JPanel {

    /**
     * Creates new form MenuCustom
     */
    private String aLebel = "Menu";
    private Icon aIcon;
    private Color aBacground1 = Color.WHITE;
    private Color aBacground2 = new Color(204, 204, 204);
    private Color aBacground3 = new Color(153, 153, 153);
    private Color aSelect = Color.BLACK;
    private Font aFont1 = new Font("Segoe UI", 0, 14);
    private Font aFont2 = new Font("Segoe UI", 1, 14);
    private static boolean aktif = true;
    private ActionListener act;

    public MenuCustom() {
        initComponents();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        pn_select = new javax.swing.JPanel();
        lb_icon = new javax.swing.JLabel();
        lb_menu = new javax.swing.JLabel();

        pn.setBackground(new java.awt.Color(255, 255, 255));
        pn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnMouseMoved(evt);
            }
        });
        pn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnMouseExited(evt);
            }
        });

        pn_select.setBackground(new java.awt.Color(68, 50, 124));

        javax.swing.GroupLayout pn_selectLayout = new javax.swing.GroupLayout(pn_select);
        pn_select.setLayout(pn_selectLayout);
        pn_selectLayout.setHorizontalGroup(
            pn_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        pn_selectLayout.setVerticalGroup(
            pn_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_menu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_menu.setForeground(new java.awt.Color(0, 0, 0));
        lb_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_menu.setText("Dashboard");

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addComponent(pn_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
            .addComponent(lb_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_select, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseMoved
        if (isAktif()) {
            pn_select.setBackground(getaSelect());
            if (pn.getBackground() != getaBacground3()) {
                pn.setBackground(getaBacground2());
            }
        }
    }//GEN-LAST:event_pnMouseMoved

    private void pnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseClicked
        if (isAktif()) {
            tekan();
        }
    }//GEN-LAST:event_pnMouseClicked

    private void pnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMouseExited
        if (isAktif()) {
            pn_select.setBackground(getaBacground3());
            if (pn.getBackground() != getaBacground3()) {
                pn.setBackground(getaBacground1());
                pn_select.setBackground(getaBacground1());
            }
        }
    }//GEN-LAST:event_pnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_menu;
    private javax.swing.JPanel pn;
    private javax.swing.JPanel pn_select;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        pn.setBackground(getaBacground1());
        pn_select.setBackground(getaBacground1());
        lb_menu.setFont(getaFont1());
        lb_menu.setText(getaLebel());
        lb_icon.setIcon(getaIcon());
    }

    public void tekan() {
        lb_menu.setFont(getaFont2());
        pn.setBackground(getaBacground3());
        act.actionPerformed(null);
    }

    /**
     * @return the aLebel
     */
    public String getaLebel() {
        return aLebel;
    }

    /**
     * @param aLebel the aLebel to set
     */
    public void setaLebel(String aLebel) {
        this.aLebel = aLebel;
        this.lb_menu.setText(aLebel);
    }

    /**
     * @return the aIcon
     */
    public Icon getaIcon() {
        return aIcon;
    }

    /**
     * @param aIcon the aIcon to set
     */
    public void setaIcon(Icon aIcon) {
        this.aIcon = aIcon;
        this.lb_icon.setIcon(aIcon);
    }

    /**
     * @return the aBacground1
     */
    public Color getaBacground1() {
        return aBacground1;
    }

    /**
     * @param aBacground1 the aBacground1 to set
     */
    public void setaBacground1(Color aBacground1) {
        this.aBacground1 = aBacground1;
    }

    /**
     * @return the aBacground2
     */
    public Color getaBacground2() {
        return aBacground2;
    }

    /**
     * @param aBacground2 the aBacground2 to set
     */
    public void setaBacground2(Color aBacground2) {
        this.aBacground2 = aBacground2;
    }

    /**
     * @return the aBacground3
     */
    public Color getaBacground3() {
        return aBacground3;
    }

    /**
     * @param aBacground3 the aBacground3 to set
     */
    public void setaBacground3(Color aBacground3) {
        this.aBacground3 = aBacground3;
    }

    /**
     * @return the aSelect
     */
    public Color getaSelect() {
        return aSelect;
    }

    /**
     * @param aSelect the aSelect to set
     */
    public void setaSelect(Color aSelect) {
        this.aSelect = aSelect;
    }

    /**
     * @return the aFont1
     */
    public Font getaFont1() {
        return aFont1;
    }

    /**
     * @param aFont1 the aFont1 to set
     */
    public void setaFont1(Font aFont1) {
        this.aFont1 = aFont1;
    }

    /**
     * @return the aFont2
     */
    public Font getaFont2() {
        return aFont2;
    }

    /**
     * @param aFont2 the aFont2 to set
     */
    public void setaFont2(Font aFont2) {
        this.aFont2 = aFont2;
    }

    /**
     * @return the aktif
     */
    public static boolean isAktif() {
        return aktif;
    }

    /**
     * @param aktif the aktif to set
     */
    public static void setAktif(boolean aktif) {
        MenuCustom.aktif = aktif;
    }

    /**
     * @return the act
     */
    public ActionListener getAct() {
        return act;
    }

    /**
     * @param act the act to set
     */
    public void setAct(ActionListener act) {
        this.act = act;
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        pnMouseClicked(evt);
    }
}
